# Generated by Django 3.2.5 on 2021-07-16 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alura_receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=100)),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('modo_preparo', models.TextField()),
                ('ingredientes', models.TextField()),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
