# Generated by Django 3.2.5 on 2021-07-17 18:24
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('alura_receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alura_receita',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
