# Generated by Django 3.2.5 on 2021-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('alura_receita', '0002_receitas_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='alura_receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
