# Generated by Django 3.2.5 on 2021-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('alura_receita', '0003_receitas_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='alura_receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
